# Generated by Django 5.1 on 2024-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
